name: Deploy to Minikube

on:
  push:
    branches:
      - '*'  # Trigger the workflow on pushes to any branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - name: Start Minikube
        run: |
          minikube start --driver=docker
      - name: Set up KubeConfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/job.yaml
          kubectl get jobs
